"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
_sym_db = _symbol_database.Default()
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
DESCRIPTOR = _descriptor.FileDescriptor(name='main.proto', package='streams', syntax='proto3', serialized_options=b'Z1git.gendocu.com/gendocu/StreamsExample.git/sdk/go', create_key=_descriptor._internal_create_key, serialized_pb=b'\n\nmain.proto\x12\x07streams\x1a\x1bgoogle/protobuf/empty.proto"\'\n\nSimpleMsg1\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\t\n\x01s\x18\x02 \x01(\t"\'\n\nSimpleMsg2\x12\x0e\n\x06number\x18\x01 \x03(\x05\x12\t\n\x01s\x18\x02 \x03(\t"Q\n\nSimpleMsg3\x12#\n\x06number\x18\x01 \x03(\x0b2\x13.streams.SimpleMsg2\x12\x1e\n\x01s\x18\x02 \x03(\x0b2\x13.streams.SimpleMsg22\xb7\x04\n\x07Example\x12;\n\nGetStream1\x12\x13.streams.SimpleMsg1\x1a\x16.google.protobuf.Empty(\x01\x12>\n\rReturnStream1\x12\x16.google.protobuf.Empty\x1a\x13.streams.SimpleMsg10\x01\x12;\n\x0bBothStream1\x12\x13.streams.SimpleMsg1\x1a\x13.streams.SimpleMsg1(\x010\x01\x12;\n\nGetStream2\x12\x13.streams.SimpleMsg2\x1a\x16.google.protobuf.Empty(\x01\x12>\n\rReturnStream2\x12\x16.google.protobuf.Empty\x1a\x13.streams.SimpleMsg20\x01\x12;\n\x0bBothStream2\x12\x13.streams.SimpleMsg2\x1a\x13.streams.SimpleMsg2(\x010\x01\x12;\n\nGetStream3\x12\x13.streams.SimpleMsg3\x1a\x16.google.protobuf.Empty(\x01\x12>\n\rReturnStream3\x12\x16.google.protobuf.Empty\x1a\x13.streams.SimpleMsg30\x01\x12;\n\x0bBothStream3\x12\x13.streams.SimpleMsg3\x1a\x13.streams.SimpleMsg3(\x010\x01B3Z1git.gendocu.com/gendocu/StreamsExample.git/sdk/gob\x06proto3', dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR])
_SIMPLEMSG1 = _descriptor.Descriptor(name='SimpleMsg1', full_name='streams.SimpleMsg1', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='number', full_name='streams.SimpleMsg1.number', index=0, number=1, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='s', full_name='streams.SimpleMsg1.s', index=1, number=2, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=52, serialized_end=91)
_SIMPLEMSG2 = _descriptor.Descriptor(name='SimpleMsg2', full_name='streams.SimpleMsg2', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='number', full_name='streams.SimpleMsg2.number', index=0, number=1, type=5, cpp_type=1, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='s', full_name='streams.SimpleMsg2.s', index=1, number=2, type=9, cpp_type=9, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=93, serialized_end=132)
_SIMPLEMSG3 = _descriptor.Descriptor(name='SimpleMsg3', full_name='streams.SimpleMsg3', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='number', full_name='streams.SimpleMsg3.number', index=0, number=1, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='s', full_name='streams.SimpleMsg3.s', index=1, number=2, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=134, serialized_end=215)
_SIMPLEMSG3.fields_by_name['number'].message_type = _SIMPLEMSG2
_SIMPLEMSG3.fields_by_name['s'].message_type = _SIMPLEMSG2
DESCRIPTOR.message_types_by_name['SimpleMsg1'] = _SIMPLEMSG1
DESCRIPTOR.message_types_by_name['SimpleMsg2'] = _SIMPLEMSG2
DESCRIPTOR.message_types_by_name['SimpleMsg3'] = _SIMPLEMSG3
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
SimpleMsg1 = _reflection.GeneratedProtocolMessageType('SimpleMsg1', (_message.Message,), {'DESCRIPTOR': _SIMPLEMSG1, '__module__': 'main_pb2'})
_sym_db.RegisterMessage(SimpleMsg1)
SimpleMsg2 = _reflection.GeneratedProtocolMessageType('SimpleMsg2', (_message.Message,), {'DESCRIPTOR': _SIMPLEMSG2, '__module__': 'main_pb2'})
_sym_db.RegisterMessage(SimpleMsg2)
SimpleMsg3 = _reflection.GeneratedProtocolMessageType('SimpleMsg3', (_message.Message,), {'DESCRIPTOR': _SIMPLEMSG3, '__module__': 'main_pb2'})
_sym_db.RegisterMessage(SimpleMsg3)
DESCRIPTOR._options = None
_EXAMPLE = _descriptor.ServiceDescriptor(name='Example', full_name='streams.Example', file=DESCRIPTOR, index=0, serialized_options=None, create_key=_descriptor._internal_create_key, serialized_start=218, serialized_end=785, methods=[_descriptor.MethodDescriptor(name='GetStream1', full_name='streams.Example.GetStream1', index=0, containing_service=None, input_type=_SIMPLEMSG1, output_type=google_dot_protobuf_dot_empty__pb2._EMPTY, serialized_options=None, create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='ReturnStream1', full_name='streams.Example.ReturnStream1', index=1, containing_service=None, input_type=google_dot_protobuf_dot_empty__pb2._EMPTY, output_type=_SIMPLEMSG1, serialized_options=None, create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='BothStream1', full_name='streams.Example.BothStream1', index=2, containing_service=None, input_type=_SIMPLEMSG1, output_type=_SIMPLEMSG1, serialized_options=None, create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='GetStream2', full_name='streams.Example.GetStream2', index=3, containing_service=None, input_type=_SIMPLEMSG2, output_type=google_dot_protobuf_dot_empty__pb2._EMPTY, serialized_options=None, create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='ReturnStream2', full_name='streams.Example.ReturnStream2', index=4, containing_service=None, input_type=google_dot_protobuf_dot_empty__pb2._EMPTY, output_type=_SIMPLEMSG2, serialized_options=None, create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='BothStream2', full_name='streams.Example.BothStream2', index=5, containing_service=None, input_type=_SIMPLEMSG2, output_type=_SIMPLEMSG2, serialized_options=None, create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='GetStream3', full_name='streams.Example.GetStream3', index=6, containing_service=None, input_type=_SIMPLEMSG3, output_type=google_dot_protobuf_dot_empty__pb2._EMPTY, serialized_options=None, create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='ReturnStream3', full_name='streams.Example.ReturnStream3', index=7, containing_service=None, input_type=google_dot_protobuf_dot_empty__pb2._EMPTY, output_type=_SIMPLEMSG3, serialized_options=None, create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='BothStream3', full_name='streams.Example.BothStream3', index=8, containing_service=None, input_type=_SIMPLEMSG3, output_type=_SIMPLEMSG3, serialized_options=None, create_key=_descriptor._internal_create_key)])
_sym_db.RegisterServiceDescriptor(_EXAMPLE)
DESCRIPTOR.services_by_name['Example'] = _EXAMPLE