/* eslint-disable */
/*Proudly generated by GenDocu.com*/
// source: main.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.streams.SimpleMsg1', null, global);
goog.exportSymbol('proto.streams.SimpleMsg2', null, global);
goog.exportSymbol('proto.streams.SimpleMsg3', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.streams.SimpleMsg1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.streams.SimpleMsg1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.streams.SimpleMsg1.displayName = 'proto.streams.SimpleMsg1';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.streams.SimpleMsg2 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.streams.SimpleMsg2.repeatedFields_, null);
};
goog.inherits(proto.streams.SimpleMsg2, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.streams.SimpleMsg2.displayName = 'proto.streams.SimpleMsg2';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.streams.SimpleMsg3 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.streams.SimpleMsg3.repeatedFields_, null);
};
goog.inherits(proto.streams.SimpleMsg3, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.streams.SimpleMsg3.displayName = 'proto.streams.SimpleMsg3';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.streams.SimpleMsg1.prototype.toObject = function(opt_includeInstance) {
  return proto.streams.SimpleMsg1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.streams.SimpleMsg1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.streams.SimpleMsg1.toObject = function(includeInstance, msg) {
  var f, obj = {
    number: jspb.Message.getFieldWithDefault(msg, 1, 0),
    s: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.streams.SimpleMsg1}
 */
proto.streams.SimpleMsg1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.streams.SimpleMsg1;
  return proto.streams.SimpleMsg1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.streams.SimpleMsg1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.streams.SimpleMsg1}
 */
proto.streams.SimpleMsg1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumber(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setS(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.streams.SimpleMsg1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.streams.SimpleMsg1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.streams.SimpleMsg1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.streams.SimpleMsg1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumber();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getS();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 number = 1;
 * @return {number}
 */
proto.streams.SimpleMsg1.prototype.getNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.streams.SimpleMsg1} returns this
 */
proto.streams.SimpleMsg1.prototype.setNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string s = 2;
 * @return {string}
 */
proto.streams.SimpleMsg1.prototype.getS = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.streams.SimpleMsg1} returns this
 */
proto.streams.SimpleMsg1.prototype.setS = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.streams.SimpleMsg2.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.streams.SimpleMsg2.prototype.toObject = function(opt_includeInstance) {
  return proto.streams.SimpleMsg2.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.streams.SimpleMsg2} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.streams.SimpleMsg2.toObject = function(includeInstance, msg) {
  var f, obj = {
    numberList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    sList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.streams.SimpleMsg2}
 */
proto.streams.SimpleMsg2.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.streams.SimpleMsg2;
  return proto.streams.SimpleMsg2.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.streams.SimpleMsg2} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.streams.SimpleMsg2}
 */
proto.streams.SimpleMsg2.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addNumber(values[i]);
      }
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addS(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.streams.SimpleMsg2.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.streams.SimpleMsg2.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.streams.SimpleMsg2} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.streams.SimpleMsg2.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumberList();
  if (f.length > 0) {
    writer.writePackedInt32(
      1,
      f
    );
  }
  f = message.getSList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * repeated int32 number = 1;
 * @return {!Array<number>}
 */
proto.streams.SimpleMsg2.prototype.getNumberList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.streams.SimpleMsg2} returns this
 */
proto.streams.SimpleMsg2.prototype.setNumberList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.streams.SimpleMsg2} returns this
 */
proto.streams.SimpleMsg2.prototype.addNumber = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.streams.SimpleMsg2} returns this
 */
proto.streams.SimpleMsg2.prototype.clearNumberList = function() {
  return this.setNumberList([]);
};


/**
 * repeated string s = 2;
 * @return {!Array<string>}
 */
proto.streams.SimpleMsg2.prototype.getSList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.streams.SimpleMsg2} returns this
 */
proto.streams.SimpleMsg2.prototype.setSList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.streams.SimpleMsg2} returns this
 */
proto.streams.SimpleMsg2.prototype.addS = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.streams.SimpleMsg2} returns this
 */
proto.streams.SimpleMsg2.prototype.clearSList = function() {
  return this.setSList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.streams.SimpleMsg3.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.streams.SimpleMsg3.prototype.toObject = function(opt_includeInstance) {
  return proto.streams.SimpleMsg3.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.streams.SimpleMsg3} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.streams.SimpleMsg3.toObject = function(includeInstance, msg) {
  var f, obj = {
    numberList: jspb.Message.toObjectList(msg.getNumberList(),
    proto.streams.SimpleMsg2.toObject, includeInstance),
    sList: jspb.Message.toObjectList(msg.getSList(),
    proto.streams.SimpleMsg2.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.streams.SimpleMsg3}
 */
proto.streams.SimpleMsg3.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.streams.SimpleMsg3;
  return proto.streams.SimpleMsg3.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.streams.SimpleMsg3} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.streams.SimpleMsg3}
 */
proto.streams.SimpleMsg3.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.streams.SimpleMsg2;
      reader.readMessage(value,proto.streams.SimpleMsg2.deserializeBinaryFromReader);
      msg.addNumber(value);
      break;
    case 2:
      var value = new proto.streams.SimpleMsg2;
      reader.readMessage(value,proto.streams.SimpleMsg2.deserializeBinaryFromReader);
      msg.addS(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.streams.SimpleMsg3.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.streams.SimpleMsg3.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.streams.SimpleMsg3} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.streams.SimpleMsg3.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumberList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.streams.SimpleMsg2.serializeBinaryToWriter
    );
  }
  f = message.getSList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.streams.SimpleMsg2.serializeBinaryToWriter
    );
  }
};


/**
 * repeated SimpleMsg2 number = 1;
 * @return {!Array<!proto.streams.SimpleMsg2>}
 */
proto.streams.SimpleMsg3.prototype.getNumberList = function() {
  return /** @type{!Array<!proto.streams.SimpleMsg2>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.streams.SimpleMsg2, 1));
};


/**
 * @param {!Array<!proto.streams.SimpleMsg2>} value
 * @return {!proto.streams.SimpleMsg3} returns this
*/
proto.streams.SimpleMsg3.prototype.setNumberList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.streams.SimpleMsg2=} opt_value
 * @param {number=} opt_index
 * @return {!proto.streams.SimpleMsg2}
 */
proto.streams.SimpleMsg3.prototype.addNumber = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.streams.SimpleMsg2, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.streams.SimpleMsg3} returns this
 */
proto.streams.SimpleMsg3.prototype.clearNumberList = function() {
  return this.setNumberList([]);
};


/**
 * repeated SimpleMsg2 s = 2;
 * @return {!Array<!proto.streams.SimpleMsg2>}
 */
proto.streams.SimpleMsg3.prototype.getSList = function() {
  return /** @type{!Array<!proto.streams.SimpleMsg2>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.streams.SimpleMsg2, 2));
};


/**
 * @param {!Array<!proto.streams.SimpleMsg2>} value
 * @return {!proto.streams.SimpleMsg3} returns this
*/
proto.streams.SimpleMsg3.prototype.setSList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.streams.SimpleMsg2=} opt_value
 * @param {number=} opt_index
 * @return {!proto.streams.SimpleMsg2}
 */
proto.streams.SimpleMsg3.prototype.addS = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.streams.SimpleMsg2, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.streams.SimpleMsg3} returns this
 */
proto.streams.SimpleMsg3.prototype.clearSList = function() {
  return this.setSList([]);
};


goog.object.extend(exports, proto.streams);
